site_name: ROSE
site_url: 'https://github.com/radical-cybertools/ROSE'
repo_name: 'ROSE'
repo_url: 'https://github.com/radical-cybertools/ROSE'
edit_uri: ""

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
  palette:
      - media: "(prefers-color-scheme: light)"
        scheme: default
        toggle:
          icon: material/weather-night
          name: Switch to dark mode
        primary: black
        accent: indigo
      - media: "(prefers-color-scheme: dark)"
        scheme: slate
        toggle:
          icon: material/weather-sunny
          name: Switch to light mode
        primary: black
        accent: indigo

  highlightjs: true
  hljs_languages:
        - yaml
        - json
        - bash
  features:
      - header.autohide
      - navigation.instant
      - navigation.top
      - navigation.tabs
      - navigation.tabs.sticky
      - search.highlight
      - search.share
      - search.suggest
      - content.code.annotate
      - content.tooltips
      - content.tabs.link
      - content.code.copy
  font:
    text: 'Segoe UI'
    code: Roboto Mono
  
  #logo: assets/rose-removebg-preview.png



# Plugins
plugins:
  - search
  - glightbox
  - minify:
      minify_html: true

# Extensions
markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - codehilite:
      linenums: true
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - attr_list
  - md_in_html

nav:
  - Home: index.md
  - Getting Started:
      - 1.Installation: getting-started/installation.md
      - 2.Dry Run: getting-started/dry-run.md
      - 3.FAQ: getting-started/faq.md
  - User Guide:
      - 1.Target Resources: user-guide/target-resources.md
      - 2.Basic ACL workflow: user-guide/basic-acl-workflow.md
      - 3.ACL Metric: user-guide/acl-metrics.md
      - 4.Advanced ACL workflow: user-guide/advanced-acl-workflow.md
      - 5.Visualization: user-guide/visualization.md

extra_css:
  - styles/custom.css

extra_javascript:
  - scripts/custom.js
